---
nvim_build_path: "{{ ansible_env.HOME }}/.build/nvim"
nvim_repo: "https://github.com/neovim/neovim.git"
nvim_install_path: "/usr/local"
nvim_remove_build: true

# defaults file for nvimBuild
nvim_build_it: no
nvim_daily_limit: false
nvim_dirs_mk: true

nvim_source: neovim/neovim

nvim_dirs:
  - "{{ ansible_env.HOME }}/.build"
  - "{{ ansible_env.HOME }}/.config"
  - "{{ ansible_env.HOME }}/.local"
  - "{{ ansible_env.HOME }}/.cache"
  - "{{ ansible_env.HOME }}/.cache/nvim"
  - "{{ ansible_env.HOME }}/.cache/nvim/swag"
  - "{{ ansible_env.HOME }}/.cache/nvim/undodir"
  - "{{ ansible_env.HOME }}/.cache/nvim/backup"
  - "{{ ansible_env.HOME }}/.cache/nvim/view"
  - "{{ ansible_env.HOME }}/.cache/nvim/spell"
  - "{{ ansible_env.HOME }}/.local/share"

nvim_dnf:
  - "@Development Tools"
  - git
  - rubygems
  - ruby-devel
  - ninja-build
  - cmake
  - unzip
  - gettext
  - curl

nvim_apts:
  - ack
  - autoconf
  - automake
  - build-essential
  - ccache
  - cmake
  - dirmngr
  - ffmpeg
  - fzy
  - g++
  - gettext
  - git
  - git-lfs
  - gperf
  - libjemalloc-dev
  - libluajit-5.1-dev
  - libmsgpack-dev
  - libtermkey-dev
  - libtool
  - libtool-bin
  - libunibilium-dev
  - libutf8proc-dev
  - libuv1-dev
  - libvterm-dev
  - lua-bitop
  - lua-ljsyscall
  - lua-lpeg
  - lua-mpack
  - lua5.1
  - luarocks
  - ninja-build
  - pandoc
  - pkg-config
  - poppler-utils
  - python3-lupa
  - software-properties-common
  - unzip
  - zsh

nvim_brews:
  - ack
  - automake
  - ccache
  - cmake
  - fd
  - fzy
  - gettext
  - git-lfs
  - libtool
  - lua
  - lua@5.1
  - luarocks
  - ninja
  - pkg-config
  - rg
  - rga

nvim_brew_heads:
  - fzf
  - luajit

nvim_gems:
  - neovim
  - minitest-neovim

nvim_perls:
  - Neovim
  # - JACQUESG/Neovim-Ext-0.05.tar.gz

...
