---
- name: clean up artifacts from prior builds
  community.general.make:
    chdir: "{{ nvim_build_path }}"
    target: distclean
    make: "{{ nvim_exe_make }}"
  tags:
    - molecule-idempotence-notest

- name: build release target
  community.general.make:
    chdir: "{{ nvim_build_path }}"
    params:
      CMAKE_BUILD_TYPE: Release
      CMAKE_INSTALL_PREFIX: "{{ nvim_install_path }}"
      # USE_BUNDLED: "OFF"
    target: install
    make: "{{ nvim_exe_make }}"
  tags:
    - molecule-idempotence-notest
...
