---
- name: create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: false
    mode: "0755"
  with_items: "{{ nvim_dirs }}"
  when: nvim_dirs_mk

- name: "build for redhat [when applicable]"
  ansible.builtin.include_tasks: tasks/redhat.yaml
  when: "'RedHat' in ansible_os_family"

- name: clone kickstart (user config)
  ansible.builtin.git:
    repo: "{{ nvim_kickstart_repo }}"
    dest: "{{ nvim_config_path }}"
    version: HEAD
    accept_hostkey: true
    clone: true
    force: false
    update: true

- name: clone source repo for build
  ansible.builtin.git:
    repo: "{{ nvim_repo }}"
    dest: "{{ nvim_build_path }}"
    version: HEAD
    accept_hostkey: true
    clone: true
    update: true
    force: true

- name: check if we built the binary in the last day
  ansible.builtin.find:
    paths: "{{ nvim_install_path }}/bin"
    patterns: nvim
    age: 1d
  register: days
  #when: nvim_build_it and (daily_limit is defined) and daily_limit

- name: "[buildrun]"
  ansible.builtin.include_tasks: tasks/build.yaml
  #when: nvim_build_it and ((days is not defined) or days.matched != '0')
